sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t crberme/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true crberme/docker-react npm run test